Homework 5
js-tasks-ru/js-20200622_toshabarinov pull request #5
Opened 2020-07-11 19:10 UTC by barinov95

2020-07-11 19:16 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-07-11 20:03 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-07-11 20:10 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-11 20:44 UTC, jsru commented
@dosandk ping :)

2020-07-12 13:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    this.body = this.element.getElementsByClassName('column-chart__chart')[0];
метод `getElementsByClassName` - возвращает коллекцию всех элементов которые имеют данных класс, или другими словами псевдо-массив
Если Вас интересует только первый найденный элемент удовлетворяющий данное условие - используйте метод `querySelector`

2020-07-12 13:13 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(appendTo = document.body) {
`appendTo` - не совсем удачное название для аргумента так как это глагол "вставь туда", используйте существительные: `root`, `element`, etc.

2020-07-12 13:15 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    <div class="notification ${this.type}" style="${'--value:' + this.duration / 1000 + 's'}">
если есть возможность не использовать конкатенацию строк - так и делайте:
```
  style="--value: ${this.duration / 1000}s"
```

2020-07-12 13:17 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let sortFunction;
эту логику было бы неплохо поправить
метод `sort` - должен отсортировать данные, а вот вставкой уже должен заниматься другой метод

2020-07-12 13:18 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this.subElements.body = this.element.getElementsByClassName('sortable-table__body')[0];
если нужен первый элемент удовлетворяющий критерий, лучше использовать метод `querySelector`

2020-07-12 13:20 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  compareNumber(first, second, cellIndex) {
такая сортировка не пойдет, зачем обращаться к DOM чтобы получить значения?
Это нужно сделать внутри JS

2020-07-12 13:20 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  compareString(first, second, cellIndex, type) {
такая сортировка не пойдет, зачем обращаться к DOM чтобы получить значения?
Это нужно сделать внутри JS

2020-07-12 13:22 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    switch (this.headers.find(header => fieldValue === header.id)?.sortType) {
не используйте выражения типа `find` внутри `switch` - это ухудшает читабельность кода, лучше вынести найденное значение в какую-то переменную и дать ей осмысленное название

2020-07-12 13:26 UTC, dosandk requested changes
В компоненте SortableTable необходимо исправить логику сортировки. Мы не сортируем DOM элементы напрямую, мы сортируем данные в JS, а после один раз перерисовываем `body` таблицы

2020-07-23 17:47 UTC, jsru commented
@dosandk ping :)

2020-07-24 12:19 UTC, dosandk approved these changes

2020-07-24 12:19 UTC, merged